"""Auto-generated Alembic script."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa825a578331'
down_revision = '8c8b8d4d1f4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zerodha_accounts', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.add_column('zerodha_accounts', sa.Column('api_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zerodha_accounts', 'api_secret')
    op.drop_column('zerodha_accounts', 'api_key')
    # ### end Alembic commands ###
